# Generated by Django 5.1 on 2025-01-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={},
        ),
        migrations.RenameField(
            model_name="session",
            old_name="date_time",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="session",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="session",
            name="transcription",
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="session",
            name="char_accuracy",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="word_accuracy",
            field=models.FloatField(),
        ),
    ]
